version: "3"
services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "8001:8000"
    restart: always

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "8080:5000"
    depends_on:
      - backend
    environment:
      - API_URL=http://backend:8000
      - PUBLIC_BACKEND_URL=http://localhost:8001
    restart: always
