apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: docker.io/sun123testdoc/availability-frontend:latest
        ports:
        - containerPort: 5000
        env:
        - name: API_URL
          value: "http://backend:8000"
        - name: PUBLIC_BACKEND_URL
          value: "http://backend:8000"
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  selector:
    app: frontend
  ports:
  - port: 5000
    targetPort: 5000
