apiVersion: v1
kind: Pod
metadata:
  name: pvc-cleaner
spec:
  containers:
  - name: cleaner
    image: busybox
    command: ["sh", "-c", "sleep 3600"]
    volumeMounts:
    - name: db-storage
      mountPath: /app/db
  volumes:
  - name: db-storage
    persistentVolumeClaim:
      claimName: db-pvc